### PR TITLE
CC-73_feat: change_password_format

### PR DESCRIPTION
**Pull request by xunli253**
The card is to add condition of at least one special character to password input.

### CODE REVIEW

**Comment by Double-Twelve** [comment]
image

The regular expression only specifies a limited number of special characters. 

If I input other characters, the error message will still appear, but I will be confused as a user because I have already met the requirements.

**Comment by Double-Twelve** [comment]
Some special characters are still missing, and you can refer to this [website](https://owasp.org/www-community/password-special-characters). 

or modify the regular expression to /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^\da-zA-Z]).{8,}$/

**Comment by Double-Twelve** [comment]
1. Your original regular expression about letters was right. _(?=.*[a-z])(?=.*[A-Z])_  it means password must contain one uppercase letter and one lowercase letter.
However, you changed to _(?=.*[A-Za-z])_ it means password must contain one letter (regardless of case).

2. The regular expression about  special characters  _(?=.*[@ `!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?~])_  "@" appears appears twice and there is a space after the first "@", what is the reason?

**Comment by xunli253** [comment]
> 1. Your original regular expression about letters was right. _(?=._[a-z])(?=._[A-Z])_  it means password must contain one uppercase letter and one lowercase letter.
>    However, you changed to _(?=.*[A-Za-z])_ it means password must contain one letter (regardless of case).
> 2. The regular expression about  special characters  _(?=._[@ `!@#$%^&_()_+-=[]{};':"\|,.<>/?~])_  "@" appears appears twice and there is a space after the first "@", what is the reason?

The seccccccc

**Comment by xunli253** [comment]
> 1. Your original regular expression about letters was right. _(?=._[a-z])(?=._[A-Z])_  it means password must contain one uppercase letter and one lowercase letter.
>    However, you changed to _(?=.*[A-Za-z])_ it means password must contain one letter (regardless of case).
> 2. The regular expression about  special characters  _(?=._[@ `!@#$%^&_()_+-=[]{};':"\|,.<>/?~])_  "@" appears appears twice and there is a space after the first "@", what is the reason?
1. I will fix the first question later. 
2. space is also a special character. So this why  there is a space after the first "@".

**Comment by Double-Twelve** [comment]
> > 1. Your original regular expression about letters was right. _(?=._[a-z])(?=._[A-Z])_  it means password must contain one uppercase letter and one lowercase letter.
> >    However, you changed to _(?=.*[A-Za-z])_ it means password must contain one letter (regardless of case).
> > 2. The regular expression about  special characters  _(?=._[@ `!@#$%^&_()_+-=[]{};':"|,.<>/?~])_  "@" appears appears twice and there is a space after the first "@", what is the reason?
> 
> 1. I will fix the first question later.
> 2. space is also a special character. So this why  there is a space after the first "@".

why "@" appears twice in   _(?=._[@ `!@#$%^&_()_+-=[]{};':"|,.<>/?~])_ ?

**Comment by xunli253** [comment]
> > > 1. Your original regular expression about letters was right. _(?=._[a-z])(?=._[A-Z])_  it means password must contain one uppercase letter and one lowercase letter.
> > >    However, you changed to _(?=.*[A-Za-z])_ it means password must contain one letter (regardless of case).
> > > 2. The regular expression about  special characters  _(?=._[@ `!@#$%^&_()_+-=[]{};':"|,.<>/?~])_  "@" appears appears twice and there is a space after the first "@", what is the reason?
> > 
> > 
> > 
> > 1. I will fix the first question later.
> > 2. space is also a special character. So this why  there is a space after the first "@".
> 
> why "@" appears twice in _(?=._[@ `!@#$%^&_()_+-=[]{};':"|,.<>/?~])_ ?

you are right. I have modified my code. please review my code again. Thank you.

**Review by Double-Twelve — APPROVED** [review]
Well done!

**Review by zhuocun — APPROVED** [review]
Cool regex!

**Comment by tatoMa** [comment]
There is a website that can easily test Regex:
https://regexr.com/

image

**Review by tatoMa — APPROVED** [review]
LGTM

**Pull request merged**
